### ISSUE TITLE
License

### ISSUE THREAD

**Issue by backspaces** [Vandivier/charm-abm#1]
Because this is a direct copy of asx, which has a GPL3 License, this also must be GPL3.

See https://github.com/backspaces/asx/blob/master/LICENSE

Also, you may simply want to fork rather than start from scratch. This makes it easier to follow asx's changes, and to collaborate with asx.

**Comment by backspaces** [comment]
Just as an aside, why not simply work on asx itself to make it suit your educational goal? I'd love to know what the issues are.

For example, if by educational you mean more NetLogo like, with a nice IDE etc, I'd love the help.

Or if you see a need in modeling semantics for education, I'd love to hear about them.

I'd suggest Medium for a good story on what an educational modeling system would look like.  I often use Medium to get good input from the community.  I've got three:

https://medium.com/dailyjs/two-headed-es6-classes-fe369c50b24
https://medium.com/@backspaces/es6-modules-part-1-migration-strategy-a48de0b7f112
https://medium.com/@backspaces/es6-modules-part-2-libs-wrap-em-up-8715e116d690

**Comment by Vandivier** [comment]
Great points and thanks for pointing out the license error.

I will consider working on asx and/or forking as an alternative, but let me make a point on the intent of this repo: The intent is not to make changes to asx but rather to use it as a package or library.

charm-abm is intended to be a specific model. I'm open to pulling this into asx's models folder so we can keep that option open.

I think the main motivation for a separate repo was to reserve the right to make weird or breaking changes without interrupting anything over there. But I'm very open to scrapping this repo and working over there, let's see after I've made a bit of progress.
